const UK_HIGHER_EDUCATION_KEYWORDS = {
  field_labels: [
    "campus name",
    "college name",
    "institution name",
    "university name",
  ],

  direct_labels: ["campus", "college", "institution", "university"],

  short_names: [
    "UCL",
    "KCL",
    "LSE",
    "QMUL",
    "SOAS",
    "RHUL",
    "UEA",
    "UWE",
    "MMU",
    "NTU",
    "BU",
    "OU",
    "UAL",
    "RCA",
    "LSBU",
    "ARU",
    "UU",
    "UoH",
  ],

  institution_names: [
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "University College London",
    "King's College London",
    "London School of Economics and Political Science",
    "University of Edinburgh",
    "University of Manchester",
    "University of Birmingham",
    "University of Bristol",
    "University of Leeds",
    "University of Glasgow",
    "University of Southampton",
    "University of Nottingham",
    "University of Liverpool",
    "University of Warwick",
    "Durham University",
    "University of St Andrews",
    "University of Bath",
    "University of York",
    "University of Exeter",
    "Queen Mary University of London",
    "University of Reading",
    "University of Sheffield",
    "University of Leicester",
    "University of Kent",
    "University of Surrey",
    "University of Sussex",
    "University of Essex",
    "University of Portsmouth",
    "University of Hertfordshire",
    "University of Hull",
    "Lancaster University",
    "Loughborough University",
    "Aston University",
    "Brunel University London",
    "Open University",
    "University of Ulster",
    "University of Aberdeen",
    "University of Strathclyde",
    "University of Plymouth",
    "University of Northampton",
    "University of East Anglia",
    "University of the West of England",
    "University of Central Lancashire",
    "Oxford Brookes University",
    "Birmingham City University",
    "De Montfort University",
    "Manchester Metropolitan University",
    "University of West London",
    "University of the Arts London",
    "Royal College of Art",
    "University of London",
    "City, University of London",
    "Goldsmiths, University of London",
    "Birkbeck, University of London",
    "SOAS University of London",
    "St George's, University of London",
    "Kingston University London",
    "Middlesex University",
    "London Metropolitan University",
    "University of Greenwich",
    "University of Bedfordshire",
    "University of Bolton",
    "University of Bradford",
    "University of Huddersfield",
    "University of Salford",
    "University of Wolverhampton",
    "University of Chester",
    "University of Lincoln",
    "University of South Wales",
    "Swansea University",
    "Cardiff University",
    "Bangor University",
    "Aberystwyth University",
    "University of Stirling",
    "Abertay University",
    "University of Dundee",
    "University of the Highlands and Islands",
    "Robert Gordon University",
    "University of the West of Scotland",
    "Edinburgh Napier University",
    "Glasgow Caledonian University",
    "University of Wales Trinity Saint David",
    "BPP University",
    "Regent's University London",
    "University for the Creative Arts",
    "York St John University",
    "Solent University",
    "Bath Spa University",
    "Canterbury Christ Church University",
    "Coventry University",
    "University of Derby",
    "University of East London",
    "University of Worcester",
    "Harper Adams University",
    "University of Suffolk",
    "University of Sunderland",
    "University of Northampton",
    "University of Lancashire",
    "University of Cumbria",
    "Falmouth University",
    "Leeds Arts University",
    "Liverpool Hope University",
    "Liverpool John Moores University",
    "Nottingham Trent University",
    "Plymouth Marjon University",
    "Sheffield Hallam University",
    "Staffordshire University",
    "Teesside University",
    "University of Plymouth",
    "University of Brighton",
    "University of Central Lancashire",
    "University of South Scotland",
    "Arts University Bournemouth",
    "Bournemouth University",
    "Edge Hill University",
    "Middlesex University London",
    "Royal Holloway, University of London",
    "University of Westminster",
    "University of Winchester",
    "University of Roehampton",
    "University of Kent",
    "University of Stirling",
    "University of Strathclyde",
    "University of Ulster",
    "Aberystwyth University",
    "Cardiff Metropolitan University",
  ],
} as const;

export const UNIVERSITY_KEYWORDS: Record<string, string[]> = {
  university_field_labels: [...UK_HIGHER_EDUCATION_KEYWORDS.field_labels],
  university_direct_labels: [...UK_HIGHER_EDUCATION_KEYWORDS.direct_labels],
  university_acronyms: [...UK_HIGHER_EDUCATION_KEYWORDS.short_names],
  uk_higher_education_names: [
    ...UK_HIGHER_EDUCATION_KEYWORDS.institution_names,
  ],
  student_id_labels: [
    "admission number",
    "admission no",
    "application id",
    "enrollment id",
    "enrollment number",
    "enrolment id",
    "enrolment number",
    "registration id",
    "registration number",
    "reg id",
    "reg no",
    "roll no",
    "roll number",
    "student id",
    "student identifier",
  ],
  employee_id_labels: [
    "employee id",
    "employee number",
    "emp id",
    "faculty id",
    "faculty number",
    "instructor id",
    "professor id",
    "staff id",
    "staff number",
  ],
  section_labels: ["batch", "class section", "cohort", "sec", "section"],
  academic_record_labels: [
    "academic standing",
    "final grade",
    "grade",
    "grade report",
    "marks",
    "score",
    "transcript id",
    "transcript number",
  ],
  financial_info_labels: [
    "fee payment",
    "fee receipt",
    "fee transaction",
    "invoice number",
    "loan account",
    "loan reference",
    "payment reference",
    "semester fee",
    "student loan",
    "fee amount",
    "tuition fee",
    "tuition fees",
  ],
  financial_context_terms: [
    "education loan",
    "fee waiver",
    "financial aid review",
  ],
  scholarship_labels: [
    "fellowship id",
    "grant id",
    "scholarship id",
    "scholarship number",
  ],
  internal_system_labels: [
    "campus portal",
    "erp",
    "faculty portal",
    "internal portal",
    "lms",
    "portal name",
    "sis",
    "student portal",
    "university portal",
  ],
  internal_system_names: [
    "Banner",
    "Blackboard",
    "Canvas",
    "Moodle",
    "PeopleSoft",
  ],
  location_labels: [
    "building",
    "dorm",
    "dormitory",
    "hostel",
    "lab",
    "laboratory",
    "residence hall",
    "room",
  ],
  location_block_labels: ["dorm block", "hostel block", "residence hall"],
  research_data_labels: [
    "dissertation title",
    "irb approval",
    "irb protocol",
    "preprint draft",
    "proprietary dataset",
    "research dataset",
    "thesis title",
    "unpublished paper",
    "unpublished research",
    "unpublished work",
  ],
  sensitive_record_labels: [
    "accommodation letter",
    "conduct case",
    "counseling record",
    "counselling record",
    "disciplinary record",
    "disability record",
    "health record",
    "medical record",
    "mental health note",
  ],
  event_participation_labels: [
    "attendee id",
    "campus event roster",
    "conference registration",
    "event participant",
    "event registration",
    "hackathon registration",
    "hackathon team",
    "participant id",
    "placement drive registration",
    "seminar participant",
    "workshop participant",
  ],
};
