import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { generateTestCases } from "@/services/testCaseGeneratorService";
import type {
  ContextDocumentRequest,
  EpicGroup,
  GenerationSettings,
  TestGeneratorRequest,
  TestGeneratorResponseData,
  WorkflowStep,
  UploadedFileMeta,
  TestGenerationState,
  GenerateTestCasesSuccessPayload,
  TestCaseStatus,
} from "@/types/testGenerator";

const initialState: TestGenerationState = {
  status: "idle",
  error: null,
  generatedData: null,
  settings: {
    format: "Structured (ID, Steps, Expected)",
    coverage: "Standard (Happy + Negative)",
    priority: "Auto-assign by risk",
    customFields: [],
  },
  generatedSettings: null,
  workflowStep: "upload",
  inputState: {
    contextDocuments: [],
    projectId: null,
    impactPrompt: "",
    tableData: [],
    originalTableData: [],
    selectedStoryIds: [],
    isJiraImport: false,
    hasInputFromPasteOrUpload: false,
    isFileUploaded: false,
    uploadedFiles: [],
    hasSavedToDb: false,
  },
  outputState: {
    testCaseStatuses: {},
    expandedTestIds: {},
    storyPageById: {},
    hasPushed: false,
  },
  lastUpdated: null,
};

function resolveResponseGenerationSettings(
  metadata: TestGeneratorResponseData["metadata"] | undefined,
  fallback: GenerationSettings,
): GenerationSettings {
  if (!metadata) {
    return fallback;
  }

  const normalizedFormat = metadata.format?.toLowerCase() || "";
  const normalizedCoverage = metadata.coverage?.toLowerCase() || "";
  const normalizedPriority = metadata.priorityMode?.toLowerCase() || "";

  const format = normalizedFormat.includes("custom")
    ? "Custom (User-defined template)"
    : normalizedFormat.includes("bdd")
    ? "BDD (Given/When/Then)"
    : "Structured (ID, Steps, Expected)";

  const coverage = normalizedCoverage.includes("comprehensive")
    ? "Comprehensive (All paths)"
    : normalizedCoverage.includes("smoke")
    ? "Smoke (Happy path only)"
    : "Standard (Happy + Negative)";

  const priority = normalizedPriority.includes("manual")
    ? "Manual"
    : normalizedPriority.includes("high")
    ? "All high"
    : "Auto-assign by risk";

  return {
    format,
    coverage,
    priority,
  };
}

export const generateTestCasesAsync = createAsyncThunk<
  GenerateTestCasesSuccessPayload,
  TestGeneratorRequest,
  { rejectValue: string }
>("testGeneration/generateTestCases", async (request, { rejectWithValue }) => {
  try {
    const response = await generateTestCases(request);

    if (!response.data) {
      return rejectWithValue(
        "The backend returned an invalid generation response.",
      );
    }

    if (response.data?.metadata?.totalTestCases === 0) {
      return rejectWithValue("No Test cases were generated by AI Provider");
    }

    return {
      generatedData: response.data,
      settings: request.settings,
      message:
        response.message || "Test case generation completed successfully.",
    };
  } catch (error) {
    return rejectWithValue(
      error instanceof Error ? error.message : "Failed to generate test cases.",
    );
  }
});

const testGenerationSlice = createSlice({
  name: "testGeneration",
  initialState,
  reducers: {
    setProjectId(state, action: PayloadAction<string | null>) {
      state.inputState.projectId = action.payload;
    },
    clearTestGenerationState(state) {
      state.status = "idle";
      state.error = null;
      state.generatedData = null;
      state.settings = initialState.settings;
      state.generatedSettings = null;
      state.workflowStep = initialState.workflowStep;
      const projectId = state.inputState.projectId;
      state.inputState = {
        ...initialState.inputState,
        projectId: projectId ?? null,
      };
      state.outputState = { ...initialState.outputState };
      state.lastUpdated = null;
    },
    clearGenerationResult(state) {
      state.status = "idle";
      state.error = null;
      state.generatedData = null;
      state.generatedSettings = null;
      state.outputState = { ...initialState.outputState };
      state.lastUpdated = null;
    },
    setWorkflowStep(state, action: PayloadAction<WorkflowStep>) {
      state.workflowStep = action.payload;
    },
    setGenerationSettings(state, action: PayloadAction<GenerationSettings>) {
      state.settings = action.payload;
    },
    setContextDocuments(
      state,
      action: PayloadAction<ContextDocumentRequest[]>,
    ) {
      state.inputState.contextDocuments = action.payload;
    },
    setImpactPrompt(state, action: PayloadAction<string>) {
      state.inputState.impactPrompt = action.payload;
    },
    setTableData(state, action: PayloadAction<EpicGroup[]>) {
      state.inputState.tableData = action.payload;
      // Deep-clone so originalTableData is always an independent snapshot.
      // Without this, Immer maps both fields to the same draft proxy (structural
      // sharing), so updateStoryInTableData mutations corrupt the baseline too.
      state.inputState.originalTableData = JSON.parse(
        JSON.stringify(action.payload),
      ) as EpicGroup[];
    },
    setSelectedStoryIds(state, action: PayloadAction<string[]>) {
      state.inputState.selectedStoryIds = action.payload;
    },

    // ── Output State: Tri-state status management ──

    setTestCaseStatus(
      state,
      action: PayloadAction<{ testCaseId: string; status: TestCaseStatus }>,
    ) {
      state.outputState.testCaseStatuses[action.payload.testCaseId] =
        action.payload.status;
    },
    bulkSetTestCaseStatus(
      state,
      action: PayloadAction<{ testCaseIds: string[]; status: TestCaseStatus }>,
    ) {
      action.payload.testCaseIds.forEach((id) => {
        state.outputState.testCaseStatuses[id] = action.payload.status;
      });
    },
    toggleExpandedTestId(state, action: PayloadAction<string>) {
      state.outputState.expandedTestIds[action.payload] =
        !state.outputState.expandedTestIds[action.payload];
    },

    setStoryPageById(
      state,
      action: PayloadAction<{ storyId: string; page: number }>,
    ) {
      state.outputState.storyPageById = {
        ...state.outputState.storyPageById,
        [action.payload.storyId]: action.payload.page,
      };
    },
    setHasPushed(state, action: PayloadAction<boolean>) {
      state.outputState.hasPushed = action.payload;
    },
    resetOutputState(state) {
      state.outputState = { ...initialState.outputState };
    },
    setIsJiraImport(state, action: PayloadAction<boolean>) {
      state.inputState.isJiraImport = action.payload;
    },
    setHasInputFromPasteOrUpload(state, action: PayloadAction<boolean>) {
      state.inputState.hasInputFromPasteOrUpload = action.payload;
    },
    setIsFileUploaded(state, action: PayloadAction<boolean>) {
      state.inputState.isFileUploaded = action.payload;
    },
    setUploadedFiles(state, action: PayloadAction<UploadedFileMeta[]>) {
      state.inputState.uploadedFiles = action.payload;
    },
    setHasSavedToDb(state, action: PayloadAction<boolean>) {
      state.inputState.hasSavedToDb = action.payload;
    },
    updateStoryInTableData(
      state,
      action: PayloadAction<{
        storyId: string;
        storyTitle: string;
        description: string;
        acceptanceCriteria: string[];
      }>,
    ) {
      const { storyId, storyTitle, description, acceptanceCriteria } =
        action.payload;
      // No break — iterate all epics so cross-project imports with the same
      // storyId in multiple epics are all kept in sync.
      for (const epic of state.inputState.tableData) {
        const idx = epic.stories.findIndex((s) => s.storyId === storyId);
        if (idx !== -1) {
          epic.stories[idx] = {
            ...epic.stories[idx],
            storyTitle,
            description,
            acceptanceCriteria,
          };
        }
      }
    },
    // Optimistically flip just-submitted stories to "in review" so the badge/block
    // update immediately, without waiting for a re-import to refetch DB status.
    markStoriesInReview(state, action: PayloadAction<string[]>) {
      const ids = new Set(action.payload);
      for (const epic of state.inputState.tableData) {
        epic.stories = epic.stories.map((s) =>
          ids.has(s.storyId)
            ? { ...s, status: "pending_approval", alreadyExists: true }
            : s,
        );
      }
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(generateTestCasesAsync.pending, (state) => {
        state.status = "inProgress";
        state.error = null;
      })
      .addCase(
        generateTestCasesAsync.fulfilled,
        (state, action: PayloadAction<GenerateTestCasesSuccessPayload>) => {
          state.status = "success";
          state.generatedData = action.payload.generatedData;
          state.generatedSettings = resolveResponseGenerationSettings(
            action.payload.generatedData.metadata,
            action.payload.settings,
          );
          state.settings = action.payload.settings;
          state.error = null;
          state.lastUpdated = new Date().toISOString();
        },
      )
      .addCase(generateTestCasesAsync.rejected, (state, action) => {
        state.status = "failed";
        state.error =
          action.payload ||
          action.error.message ||
          "Failed to generate test cases.";
        state.generatedData = null;
        state.lastUpdated = new Date().toISOString();
      });
  },
});

export const {
  clearTestGenerationState,
  clearGenerationResult,
  setWorkflowStep,
  setGenerationSettings,
  setContextDocuments,
  setImpactPrompt,
  setTableData,
  setSelectedStoryIds,
  setTestCaseStatus,
  bulkSetTestCaseStatus,
  toggleExpandedTestId,
  setStoryPageById,
  setHasPushed,
  resetOutputState,
  setIsJiraImport,
  setHasInputFromPasteOrUpload,
  setIsFileUploaded,
  setUploadedFiles,
  setHasSavedToDb,
  setProjectId,
  updateStoryInTableData,
  markStoriesInReview,
} = testGenerationSlice.actions;
export default testGenerationSlice.reducer;
